### ISSUE TITLE
Memory usage grows over time

### ISSUE THREAD

**Issue by philmayers** [google/mtail#61] opened 2017-06-01 14:31 UTC
We're using mtail with a local ruleset to process logs from the Exim MTA. This has been running since Mar 30th and is now using 1.8G of RAM. The ruleset is a fairly simple set of regexp incrementing some counters - will attach examples and a /debug/pprof

Any thoughts?

**Comment by philmayers** [comment] 2017-06-01 14:38
Debug pprof & heap, varz format of counters at this gist

https://gist.github.com/philmayers/35d248ccb887f24192fbfbd45d6bf75e

Let me know if you need the ruleset, I'll sanitise and post it. The copy of mtail we're running was built with Go 1.7 and from revision 431f5c7

**Comment by jaqx0r** [comment] 2017-06-01 20:58
The mtail program will be useful. If you're using dimensioned variables
based on, say, pods or usernames or other time-local information that will
continue to hang around.

There is a del built-in that you can use to signal that the variable is no
longer used, but it's not very elegant imho and probably has races with
data export -- it is best used only on hidden vars.

Thanks for the report!

**Comment by philmayers** [comment] 2017-06-02 10:08
As the varz I posted hopefully shows, we're not doing high-cardinality dimensioned variables. As such I am assuming that 1.8G of RAM (and growing) is not expected.

We *are* using 2 hidden vars temporarily as accumulators during each pass through the ruleset but they're not dimensioned - I'm assuming it's not this.

**Comment by jaqx0r** [comment] 2017-06-03 00:38
Thanks for the info.  It does sound like some memory is being referenced
and not being garbage collected as a result, so the heap dump should help.
I'll let you know if I can't repro it and need the program.

**Comment by jaqx0r** [comment] 2017-06-27 08:37
I'm having trouble reproducing this with just the heap, but it's given me a clue as to what's leaking.  Could you provide me with the mtail program and a snippet of exim log?

**Comment by jaqx0r** [comment] 2017-06-28 08:50
Please try again with the latest release and go 1.8.  The storage has had some changes since your report and I would like some fresh data.

**Comment by philmayers** [comment] 2017-06-28 13:45
We'll re-test and update. The mtail program is not a problem but the exim logs obviously contain personal data - I'd need to extract a safe subset. Do you still need these or should we retest with the newer code/go first?

**Comment by jaqx0r** [comment] 2017-06-29 12:28
Ah OK.  Please just retest with the newer code first, and recapture the
heap and cpu profiles, and the mtail program.  I think I can work with that
and won't need the log.

**Comment by jaqx0r** [comment] 2017-08-08 05:31
Current state: building a  go1.7.6  toolchain to build an mtail to profile your heap against.

**Comment by jaqx0r** [comment] 2017-08-08 05:34
Huh:

```
(pprof) top
1521.82MB of 1524.89MB total (99.80%)
Dropped 149 nodes (cum <= 7.62MB)
      flat  flat%   sum%        cum   cum%
 1162.81MB 76.26% 76.26%  1162.81MB 76.26%  github.com/google/mtail/tailer.(*Tailer).TailFile
...
(pprof) list TailFile
Total: 1.49GB
ROUTINE ======================== github.com/google/mtail/tailer.(*Tailer).TailFile in /home/jaq/go/src/github.com/google/mtail/tailer/tail.go
    1.14GB     1.14GB (flat, cum) 76.26% of Total
...
    1.14GB     1.14GB    125:	logCount.Add(1)
...
```

A gig for a counter.  What??

**Comment by jaqx0r** [comment] 2017-08-08 05:40
I am not sure I trust this.  I checked out 431f5c7 and built with my go1.7.6 toolchain, and the heap is unmodified.

(I tried editing the heap dump to update the filepaths to my copy, but turns out that is unnecessary, I get the same results with both.)

@philmayers You never responded to my request for reproduce with the latest version of the code.  Are you still interested in doing this?  (FWIW I was wrong to ask you for the program and logs, now I think I know what I'm doing with the profile tool, but back then I had no idea.)

**Comment by jaqx0r** [comment] 2017-08-08 06:00
Pretty sure that's an off-by-one error. 
```
(pprof) focus=TailFile
(pprof) top
1.14GB of 1.49GB total (76.26%)
Dropped 3 nodes (cum <= 0.01GB)
      flat  flat%   sum%        cum   cum%
    1.14GB 76.26% 76.26%     1.14GB 76.26%  github.com/google/mtail/tailer.(*Tailer).TailFile /home/jaq/go/src/github.com/google/mtail/tailer/tail.go:125
         0     0% 76.26%     1.14GB 76.26%  github.com/google/mtail/tailer.(*Tailer).startNewFile /home/jaq/go/src/github.com/google/mtail/tailer/tail.go:305
         0     0% 76.26%     1.14GB 76.26%  github.com/google/mtail/tailer.New /home/jaq/go/src/github.com/google/mtail/tailer/tail.go:66
         0     0% 76.26%     1.14GB 76.26%  strings.indexShortStr /home/jaq/src/golang/go/src/runtime/asm_amd64.s:1713
```

I am still confused by this because the `web` output shows the call tree in the reverse order.

**Comment by philmayers** [comment] 2017-08-08 09:55
Sorry for the late reply, I am in the process of preparing to leave my current employer.

We did rebuild using latest Go and mtail - will update shortly with the exact versions, but current as of ~early July - and it is still showing the same behaviour.

**Comment by jaqx0r** [comment] 2017-08-08 11:11
Thanks.  Good luck in the future!

Can you get me a heap dump with the version you're running?

**Comment by philmayers** [comment] 2017-08-22 12:52
Heap dump from aforementioned version

https://gist.github.com/philmayers/f0c459570904c60619ed60d0c19a8c1c

**Comment by jaqx0r** [comment] 2017-08-23 08:29
Thanks!

**Comment by jaqx0r** [comment] 2017-08-26 12:57
This latest heap shows 440MB in use, 345MB of which was allocated by Tailer.read() , line 166 which is where the log input is read into memory.

This particular heap is not over a gigabyte, so I don't think it's exhibiting the problem.  Also, 345MB is a lot of RAM to be pinned in memory but it's not awful.

Using `go tool pprof --alloc_space ~/go/bin/mtail ~/heapy.txt` on tthe revision you posted earlier and your heap as heapy.txt I see read is still the highest allocator overall with 93% of total allocations.

What might be happening is the pinned RAM is not GC'd because partials are being referenced by the metric storage.  I don't know how the internals of the regexp.FindStringSubmatch work but it's not making new allocations (only 0.69%) so I wonder if it's using pointers to the line read and thus keeping the whole original allocation pinned.

I can also imagine then that we're not seeing 1.8G of allocation in this heap because GC got better between the original bug report and now go 1.8.3, and perhaps the older version couldn't make the decision to free the RAM it does now.

Is the vss of the process about 800-900MB when you get the heap dump?  (e.g. ps aux | grep mtail)  On an unladen mtail, freshly started, with no logs processed I see it using 400MB VSS and internally claims it's only allocated a 2MB, so I expect with 440MB in the heap profile to have 400MB of... go runtime I guess.

Will need to hunt down why the log partials are being kept pinned in RAM.  I think it's not egregious now, and perhaps go 1.8's GC is why this is better today than it was when you first reported it, but it's still very interesting.

**Comment by philmayers** [comment] 2017-08-26 13:15
It's hard to be absolutely certain since the servers don't have identical workloads, but when we upgraded this single node to the newer mtail/go version, we left the existing ones as-was - they appear to be growing at the same sort of rate, so the lower usage *might* just be uptime related.

ps for the newer one reads

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
mtail     2207  2.0 15.8 2121748 1279448 ?     Sl   Aug04 645:55 /usr/local/bin/mtail -progs /etc/mtail
```

i.e. about 2GB, and about 1.2GB RSS. pmap in case it's helpful, which matches the above:

https://gist.github.com/philmayers/971412d6070a7944f4e68c3ca9736829

I'll try and look at our influx/grafana stats next week to see if the memory usage has tailed off. If this is just baseline Go memory usage, then it should stop climbing over time, which it didn't on the older version.

Will update once I've had a chance to investigate.

**Comment by jaqx0r** [comment] 2017-08-26 14:46
Indeed, https://blog.golang.org/go-slices-usage-and-internals says that sliced arrays retain the original array even if the only live references are a small subset.  regexp.FindStringSubmatch returns slices of the original string, so unless I've cleverly copied them in the VM, and it looks like I haven't, then that's going to be one reason for the unexpectedly large pinned RAM.

Oh almost missed this update. Thanks for the extra details, sounds like I would be wrong to assume a go behaviour change then (in GC).  I'm curious why your heap only had 440MB of in-use when your vsize is so big.  I'd believe that the runtime is hanging onto RAM and not handing it back to the OS, but I don't know how to find that out.

**Comment by jaqx0r** [comment] 2017-08-30 01:43
I've discovered that the example and benchmark tests do not exercise the
tailer's read path so I cannot test my hypothesis without manually
constructing the test.  So I'm knee deep in a refactoring to make the tests
use the same codepath as production...

Once that's done, I can test my theory about string slices pinning the
whole string to prevent GC and thus causing the usage.

**Comment by jaqx0r** [comment] 2018-06-10 08:18
I can't repro this, and it's a year old so closing.  Happy to have it opened again with more information.

**Closed by jaqx0r** 2018-06-10 08:18 UTC
Labels: #noideadog, bug, help wanted

**Comment by acamari** [comment] 2026-04-30 22:31
Hi, I'm getting memory constantly increasing in size, I can help debugging this but I'm not that familiar with the go ecosystem.

We're using: `mtail version 3.0.0~rc52 git revision 3.0.0~rc52-1ubuntu0.3 go version go1.22.2 go arch amd64 go os linux
`
In ubuntu 24LTS

for example mtail processes reached 2.5-3GB (during 40 days) before oom killer thought it was too juicy.

I attach mtail programs:

[mtail_haproxy.txt](https://github.com/user-attachments/files/27263376/mtail_haproxy.txt)
[lkf_script.txt](https://github.com/user-attachments/files/27263375/lkf_script.txt)
[lkf_backend.txt](https://github.com/user-attachments/files/27263374/lkf_backend.txt)

Please let me know if I can provide any relevant info...

**Comment by jaqx0r** [comment] 2026-04-30 23:26
Please file a new issue in jaqx0r/mtail -- but you can start with https://github.com/jaqx0r/mtail/blob/main/docs/Troubleshooting.md#memory-or-performance-issues as a primer on memory troublesotting, and have a look at https://github.com/jaqx0r/mtail/issues/390 to see if they're similar.
