### ISSUE TITLE
mtail keeps on running if producer crashes when reading from stdin

### ISSUE THREAD

**Issue by ema** [google/mtail#331] opened 2020-07-29 09:22 UTC
Hi!

Wikimedia uses mtail for various purposes, including exposing varnish statistics. To do that, we've got a very simple shell script called [varnishmtail](https://gerrit.wikimedia.org/r/plugins/gitiles/operations/puppet/+/refs/heads/production/modules/varnish/files/varnishmtail). As you can see, the script boils down to `varnishncsa | mtail -logs /dev/stdin`. We used to run mtail with `-logfds 0` and then moved to `-logs /dev/stdin` when `-logfds` was removed (see [this comment on mtail issue #3](https://github.com/google/mtail/issues/3#issuecomment-511341389)).

Now, there's a problem we've discovered recently. If the producer dies (varnishncsa in this case) mtail keeps on running normally, hence the `varnishmtail` script keeps on running, and the systemd unit responsible for the whole thing does not notice anything. However, for all purposes the system is at that point not functioning, given that stats aren't updated any longer. See a more detailed description on [our bug tracking system](https://phabricator.wikimedia.org/T259020).

I think that, in the special case of when mtail is reading from stdin, receiving `EOF` should make the process exit. Thoughts?

**Comment by jaqx0r** [comment] 2020-07-30 04:09
That sounds like a good idea.

I wonder if there are any weird effects by doing so though, does it need
another flag to turn on that behaviour? I think it doesn't, if there are no
other log files open to read and the FD closes then it seems there's
nothing it can do afterwards.

In the interim if you're using bash can you turn on pipefail mode to make
the shell kill mtail?

**Comment by ema** [comment] 2020-07-30 07:54
> I wonder if there are any weird effects by doing so though, does it need another flag to turn on that behaviour? I think it doesn't, if there are no other log files open to read and the FD closes then it seems there's nothing it can do afterwards. 

I also don't think another flag is needed.

> In the interim if you're using bash can you turn on pipefail mode to make the shell kill mtail?

That is the first thing I thought of doing too! However, pipefail is about the exit status of the pipeline, not about making any command stop. If mtail keeps on running, the shell waits for it whether pipefail is enabled or not.

**Comment by jaqx0r** [comment] 2021-01-15 00:34
As of HEAD right now I think that `mtail` will exit properly when stdin is closed if you only have one log (`/dev/stdin`) and you also add the flag `--one_shot`.

I want to remove the need for using `--one_shot` because that is supposed to be a debugging flag, so the issue isn't resolved yet.

**Comment by shogos3** [comment] 2021-03-05 08:15
> 
> I want to remove the need for using `--one_shot` because that is supposed to be a debugging flag, so the issue isn't resolved yet.

Please do this. Because it looks `--one_shot` does not support bucket. I deserve to use stdin with bucket.

Thanks!

**Comment by jaqx0r** [comment] 2024-04-27 13:34
There's a bit to untangle here.

The tailer can easily shut itself down once there are no more log patterns to watch; i.e. when stdin is closed it is removed from the pattern list.

The VM runtime can shut down once the tailer has closed the lines channel.

The hard part is getting the exporter and http server to close once the VM is done.  There's some TODOs I left around indicating I should do better with the server shutdown code which give me some hints.

**Comment by jaqx0r** [comment] 2024-05-07 12:15
Well it turns out it's not so easy to shut down the tailer because it is _also_ looking for new log patterns, so it needs to know that there are no more logstreams, and that there will never be any more logstreams.

I think I have figured out a way to make that happen, needs a bit more refactoring in the pattern globbing code.

**Closed** 2024-05-26 16:13 UTC
Labels: bug, mtail-Operating
