### ISSUE TITLE
Support including hidden metric as label of another metric

### ISSUE THREAD

**Issue by david-vavra** [google/mtail#140] opened 2018-01-22 10:43 UTC
Hi, 
another proposal, in some sense similar to https://github.com/google/mtail/issues/139. It would be also nice to have an ability to include (hidden) metric as a label of another metric. 

An example: 
```
hidden gauge state
counter state_exported by state

/^0$/ {
  state = 0
}

/^[1-9][0-9]*$/ {
  state += 1
}

state_exported[state]++
```

Thank you for considering.

**Comment by jaqx0r** [comment] 2018-06-08 00:50
OK I think I know what needs to happen; we don't have a way to fetch the value of a metric, only to set or increment it.  Implementing this should be straightforward but requires changing the virtual machine and the compiler a bit.

**Comment by jaqx0r** [comment] 2018-06-08 00:52
Just realised this is a duplicate of #116

**Closed** 2018-06-10 08:13 UTC
Labels: duplicate, enhancement
