### ISSUE TITLE
Support for matching hidden metric in addition to regex groups

### ISSUE THREAD

**Issue by david-vavra** [google/mtail#139] opened 2018-01-22 10:20 UTC
Hello, 
it would be nice to have an ability to match not only regex groups but also (hidden) metrics. This would allow us to keep state in between different log lines. 

Simple example: 
```
hidden gauge state

/^0$/ {
  state = 0
}

/^[1-9][0-9]*$/ {
  state += 1
}

state < 3 {
    DO_SOMETHING
}

state >= 3 {
    DO_SOMETHING_ELSE
}
```
Thank you for considering.

**Comment by jaqx0r** [comment] 2018-06-08 00:51
I think this is going to require the same work as in #140.

**Comment by jaqx0r** [comment] 2018-06-08 00:53
Also, a dupe of #116

**Comment by Loki087** [comment] 2018-06-09 14:00
Hi, there is a trick to make variables comparison:

hidden gauge linecounter by service
...
0+linecounter[getfilename()] != 100 {
...
}

Idea is to make math operation to force mtail vm make correct type converstion. in this example  we add zero "0+" to not change the value but to convert variable to correct type.

You can use same trick with mtail functions:
0+timestamp()-hidden_tmstmp >= 3600
or you can save timestamp and use it between multiple blocks(for example if you parse multiline string where timestamp is only in one first line)
settime(0+store_timestamp[getfilename()]) to play with current time

**Closed** 2018-06-10 08:13 UTC
Labels: duplicate, enhancement
