### ISSUE TITLE
"failed to marshal metrics into json" due to +Inf

### ISSUE THREAD

**Issue by gsstark** [google/mtail#273] opened 2019-10-31 15:35 UTC
I'm getting this error when running mtail with -one_shot mode:

```
Metrics store:E1031 11:27:10.506026   50999 main.go:179] failed to marshal metrics into json: json: unsupported value: +Inf
```

I started getting this error when I first added a histogram which makes me think it has to do with the le=+Inf  label. But I haven't dug any deeper yet.

**Comment by jaqx0r** [comment] 2019-11-06 11:14
Can you share the whole command line please?
Did you do anything other than run the command?

JSON is not well supported, it started as a hack to test metrics and needs
to be removed. I wanna ask, do you care particularly about the format of
results from one_shot?

Also it'd help make a test case to reproduce if you can share the program
you're writing.

**Comment by Lusitaniae** [comment] 2019-11-28 09:39
I see the same

nginx.mtail
```
counter http_requests_total by method, code, content_type
counter http_request_duration_milliseconds_sum by method, code, content_type
counter http_response_size_bytes_sum by method, code, content_type
histogram http_request_duration_miliseconds by method, code buckets 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 15

/^/ +
/(?P<proxy_addr>[0-9A-Za-z\.\-:]+) / +
/- / +
/(?P<remote_user>[0-9A-Za-z\-]+) / +
/(?P<time_local>\[\d{2}\/\w{3}\/\d{4}:\d{2}:\d{2}:\d{2} \+\d{4}\]) / +
/"(?P<request_method>[A-Z]+) (?P<request_uri>\S+) (?P<http_version>HTTP\/[0-9\.]+)" / +
/(?P<status>\d{3}) / +
/(?P<bytes_sent>\d+) / +
/(?P<request_seconds>\d+)\.(?P<request_milliseconds>\d+) / +
/"(?P<http_referer>\S+)" / +
/"(?P<http_user_agent>[[:print:]]+)" / +
/"(?P<content_type>.+)" / +
/"(?P<remote_addr>[0-9A-Za-z\.\-:]+)"/ +
/$/ {
  http_requests_total[tolower($request_method)][$status][$content_type]++
  http_request_duration_milliseconds_sum[tolower($request_method)][$status][$content_type] += $request_seconds * 1000 + $request_milliseconds
  http_request_duration_miliseconds[tolower($request_method)][$status] = $request_seconds * 1000 + $request_milliseconds
  http_response_size_bytes_sum[tolower($request_method)][$status][$content_type] += $bytes_sent
}
```

logs
```

1.1.1.1 - - [28/Nov/2019:08:06:43 +0000] "POST /user/12593/edit HTTP/1.1" 200 7257 1.164 "https://web.site.com/user/12593/edit" "Mozilla/5.0 (Linux; Android 6.0; SMART 4G M1 Plus) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Mobile Safari/537.36" "application/json" "223.24.61.142"
```

command
```
./mtail --one_shot --progs ~/mtaild/ --logs ~/mtaild/nginx.log -v=10 -logtostderr
```

**Comment by finkr** [comment] 2020-02-04 16:47
looks like a duplicate of https://github.com/google/mtail/issues/223
Buckets and `-one_shot` don't work together.

**Closed** 2020-03-28 22:37 UTC
