### ISSUE TITLE
del after duration / expire not working 

### ISSUE THREAD

**Issue by chaudhryfaisal** [google/mtail#202] opened 2019-01-16 04:03 UTC
### mtail version
```shell
mtail version  git revision  go version go1.11.4 go arch amd64 go os darwin
git revision f8eca1029c15a6a9d3c125bb9d5771a0a6cc4b42 
```

#### what happened
trying to test expire metric by following **linecount.mtail** :

```
counter line_count_1 by a
counter line_count_2

/$/ {
  line_count_1["a"]++
  del line_count_1["a"] after 30s

  line_count_2++
  del line_count_2 after 30s
}

```

```shell
I0115 21:57:33.034933   56251 main.go:91] mtail version  git revision  go version go1.11.4 go arch amd64 go os darwin
I0115 21:57:33.035145   56251 main.go:92] Commandline: ["/private/var/folders/sd/n7x4tn6j0vz9jqn00w901ss95pmzml/T/___run" "--logtostderr" "--progs" "mtail/__test/linecount.mtail" "--logs" "mtail/__test/sample.log"]
I0115 21:57:33.035949   56251 loader.go:219] Loaded program linecount.mtail
I0115 21:57:33.035959   56251 loader.go:238] Program linecount.mtail has goroutine marker 0x6c696e65
I0115 21:57:33.035992   56251 vm.go:749] Starting program linecount.mtail
I0115 21:57:33.035998   56251 loader.go:242] Started linecount.mtail
I0115 21:57:33.036428   56251 tail.go:254] Tailing mtail/__test/sample.log
I0115 21:57:33.036544   56251 mtail.go:251] Listening on [::]:3903
```

#### browser output
```
# TYPE line_count_1 counter
# line_count_1 defined at linecount.mtail:1:9-20
line_count_1{a="a",prog="linecount.mtail"} 3
# TYPE line_count_2 counter
# line_count_2 defined at linecount.mtail:2:9-20
line_count_2{prog="linecount.mtail"} 3
```

#### expected behavior
line_count_1 and line_count_2 to be deleted after `30s`

#### actual behavior
none of the metrics expire

**Comment by jaqx0r** [comment] 2019-01-18 06:15
I noticed this a few days ago, it's fixed in db51966fd590ba1f4904b57859adaca6a7c05d27 and in the just released https://github.com/google/mtail/releases/tag/v3.0.0-rc18

Please get the latest and let me know if you still have this problem, thanks!

**Comment by chaudhryfaisal** [comment] 2019-01-18 16:40
@jaqx0r Issue still seems to be there. I tried both with latest in master branch [38039ce](https://github.com/google/mtail/commit/6880a50008c13c45f9484f9deaf9a19f138039ce)  and release `v3.0.0-rc18`

**Comment by chaudhryfaisal** [comment] 2019-01-24 20:08
can you please re open this bug? 
Thank you

**Comment by jaqx0r** [comment] 2019-01-29 03:17
Sure, I was on vacation so I'm sorry I couldn't reopen it straight away.

**Comment by chaudhryfaisal** [comment] 2019-01-29 20:01
welcome back 😄

**Comment by jaqx0r** [comment] 2019-01-30 10:20
Alright... I think the problem is that we only expire metrics once an hour.

https://github.com/google/mtail/blob/master/internal/metrics/store.go#L129

So for your test, if you reduce that ticker to time.Minute and recompile, does it work after a minute?  Or if you don't want to recompile, can you wait an hour to see if the metrics are gone?

**Comment by chaudhryfaisal** [comment] 2019-01-30 17:39
great, let me try that.
quick question on this topic, would there be any performance concern if the ticker is set to 5min? we plan on having 2k-5k unique metrics and curious why ticker is currently set to 1 Hour right now.

**Comment by chaudhryfaisal** [comment] 2019-01-30 18:42
Found another bug? 
https://github.com/google/mtail/blob/master/internal/metrics/store.go#L130 is missing `for` loop around it?
I made the interval configurable and it only triggered `Expire` function once. after adding some additional logging here are my results before and and after adding `for` loop

**Before**
```go
select {
case <-ticker.C:
	err := s.Expire()
	if err != nil {
		glog.Info(err)
	}
}
```
```bash
I0130 12:35:36.534250   98544 store.go:130] Configuring StartExpiryLoop with 5s
I0130 12:35:36.534349   98544 mtail.go:252] Listening on [::]:3903
I0130 12:35:41.535539   98544 store.go:105] Running Store.Expire()
```

**After**
```go
for {
	select {
	case <-ticker.C:
		err := s.Expire()
		if err != nil {
			glog.Info(err)
		}
	}
}
```
```bash
I0130 12:40:21.404008   99309 store.go:130] Configuring StartExpiryLoop with 5s
I0130 12:40:21.404061   99309 mtail.go:252] Listening on [::]:3903
I0130 12:40:26.405461   99309 store.go:105] Running Store.Expire()
I0130 12:40:31.407042   99309 store.go:105] Running Store.Expire()
I0130 12:40:36.408163   99309 store.go:105] Running Store.Expire()
```

**Comment by jaqx0r** [comment] 2019-01-30 21:44
Thanks!

No reason other than I wanted to err on the side of caution.

**Comment by jaqx0r** [comment] 2019-01-31 08:41
pull/205 fixes this.  Thanks for that!

**Closed by jaqx0r** 2019-01-31 08:41 UTC
Labels: bug
