### ISSUE TITLE
-logs suports multiple files in different directories

### ISSUE THREAD

**Issue by benamazing** [google/mtail#260] opened 2019-08-29 08:05 UTC
Hi, my log directory structure is as follows:

/data/logs/<app_name>/<app_instance>.log

but it appears that -logs command line option doesn't support such pattern (multiple depths), is it possible to enhance it?

**Comment by jnovack** [comment] 2019-09-09 20:36
Dupe of #200, please close.

**Closed** 2019-12-12 03:08 UTC
