### ISSUE TITLE
Programs with errors can crash mtail

### ISSUE THREAD

**Issue by TheTincho** [google/mtail#37] opened 2016-07-18 02:07 UTC
I was testing some modifications to a program, and I noticed that mtail reloaded it immediately, without me having the chance to run it with `-compile_only`. Moreover, something in the program made it crash completely:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x57cc71]

goroutine 1 [running]:
panic(0x88b600, 0xc82000e0e0)
    /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/google/mtail/vm.(*compiler).compile(0xc8201f7668, 0x7a3a40, 0xc82007ba20)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/vm/compiler.go:194 +0x5411
github.com/google/mtail/vm.(*compiler).compile(0xc8201f7668, 0x7a36e0, 0xc8201405a0)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/vm/compiler.go:121 +0x1864
github.com/google/mtail/vm.(*compiler).compile(0xc8201f7668, 0x7a3800, 0xc820140630)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/vm/compiler.go:83 +0xf07
github.com/google/mtail/vm.(*compiler).compile(0xc8201f7668, 0x7a3f20, 0xc82007ba00)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/vm/compiler.go:68 +0x14a
github.com/google/mtail/vm.(*compiler).compile(0xc8201f7668, 0x7a3800, 0xc8201409f0)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/vm/compiler.go:91 +0x105b
github.com/google/mtail/vm.(*compiler).compile(0xc8201f7668, 0x7a3f20, 0xc82007a2e0)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/vm/compiler.go:68 +0x14a
github.com/google/mtail/vm.Compile(0xc82007a28b, 0x14, 0x7fcdc416e4a8, 0xc82007e020, 0xc8201400c0, 0x101, 0x91bcf8, 0x0, 0x0)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/vm/compiler.go:43 +0x41f
github.com/google/mtail/vm.(*Loader).CompileAndRun(0xc820078420, 0xc82007a28b, 0x14, 0x7fcdc416e4a8, 0xc82007e020, 0x0, 0x0)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/vm/loader.go:98 +0x8f
github.com/google/mtail/vm.(*Loader).LoadProg(0xc820078420, 0xc82007a280, 0x1f, 0x0, 0x0)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/vm/loader.go:89 +0x3c0
github.com/google/mtail/vm.(*Loader).LoadProgs(0xc820078420, 0x7fffa7fc4888, 0xa, 0x0, 0x0)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/vm/loader.go:67 +0x5ed
github.com/google/mtail/mtail.(*Mtail).InitLoader(0xc820148000, 0x0, 0x0)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/mtail/mtail.go:121 +0x180
github.com/google/mtail/mtail.New(0x7fffa7fc4888, 0xa, 0xc82013e0e0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x91b6c8, 0x4, ...)
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/mtail/mtail.go:164 +0x175
main.main()
    /build/mtail-0.0+git20160704.35c4023/build/src/github.com/google/mtail/main.go:66 +0x5d2
```

**Comment by jaqx0r** [comment] 2016-07-18 03:59
Doh, that should not be happening! It should be printing the compile errors
to the log and leaving the old program in place.

I suspect the crash is in the compiler.

**Comment by TheTincho** [comment] 2016-07-19 02:41
Funny thing: I did not get a single compile error, just crashes.
Another weird thing is that when some kind of error was made in the program, instead of giving any error, it will just not show it as loaded. It'd just silently skip it (although the metric definitions showed up in /metrics)

**Comment by jaqx0r** [comment] 2016-07-19 05:33
the crash in the compiler will prevent the errors from being emitted, but I
suspect you've found something that wouldn't even trap an error because it
crashed instead.

There's an odd ordering of events that causes the metrics to get created
even if the program is bad, that's why you see them.  I have a refactoring
on progress that should make the recompile safer and more obvious.

The crash you've found I should have fixed this week, time permitting.

Can you share the program that made it crash?

**Comment by jaqx0r** [comment] 2016-07-25 02:52
Can you share the program that made it crash?

Can you reproduce this with the code at HEAD?

**Comment by TheTincho** [comment] 2017-01-13 22:05
Hey, sorry I only see this now! For some reason I've lost many github notifications...

Sadly, I don't have that program any more.

**Comment by jaqx0r** [comment] 2017-01-30 10:10
Closing as there's no longer enough to reproduce it.

**Closed by jaqx0r** 2017-01-30 10:10 UTC
